# Generated by Django 5.2.6 on 2025-11-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("ingredients", models.TextField()),
                ("instructions", models.TextField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "ingredients", "instructions"],
                        name="recipe_reci_name_4add7a_idx",
                    )
                ],
            },
        ),
    ]
