# Generated by Django 5.2.6 on 2025-09-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("technologies", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="project_images/")),
                (
                    "project_url",
                    models.URLField(
                        blank=True, help_text="The URL to the project's website."
                    ),
                ),
                (
                    "is_makeitexist_app",
                    models.BooleanField(
                        default=True, help_text="Is this an app for makeitexist.net?"
                    ),
                ),
                (
                    "display_domain",
                    models.CharField(
                        blank=True,
                        help_text="The domain name to display (e.g., clownfishgenetics.org)",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
