# Generated by Django 5.2.6 on 2025-11-06 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0004_staffmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="display_domain",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The domain name to display (e.g., clownfishgenetics.org)",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format:'+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
