# Generated by Django 5.2.6 on 2025-11-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_slug_post_is_published_alter_post_pub_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
