# Generated by Django 5.2.6 on 2025-11-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
