# Generated by Django 5.2.6 on 2025-11-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pantry", "0004_alter_stock_batch_number_alter_stock_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stock",
            name="batch_number",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="storageunit",
            name="notes",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
