# Generated by Django 5.2.6 on 2025-11-03 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "repo_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("owner", models.CharField(max_length=100)),
                ("html_url", models.URLField()),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "sha",
                    models.CharField(
                        max_length=40, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("message", models.TextField()),
                ("author_name", models.CharField(max_length=100)),
                ("author_email", models.EmailField(max_length=254)),
                ("date", models.DateTimeField()),
                ("html_url", models.URLField()),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="github_feed.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "repository__name"],
            },
        ),
    ]
