# Generated by Django 5.2.6 on 2025-11-04 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github_feed", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repository",
            options={"ordering": ["name"], "verbose_name_plural": "Repositories"},
        ),
    ]
